language: cpp

compiler:
  - gcc
  - clang
  
matrix:
  include:
    - compiler: gcc
      os : linux
    - compiler: clang
      os : linux
    - compiler: gcc
      os : osx
      env : OSX_GENERATOR="make"
    - compiler: clang
      os : osx
      env : OSX_GENERATOR="make"
    - compiler: gcc
      os : osx
      env : OSX_GENERATOR="Xcode"
    - compiler: clang
      os : osx
      env : OSX_GENERATOR="Xcode"
    
  
  allow_failures:
  - os: osx 
  
before_script:
  - sh .ci/travis-deps.sh
  
script:
  - sh .ci/travis-build.sh

notifications:
  email:
    - pegua1@gmail.com
